name: 'Terraform CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: 'eu-west-2'
  TF_VERSION: '1.13.0'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Setup Terragrunt
      run: |
        sudo wget -q -O /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64"
        sudo chmod +x /usr/local/bin/terragrunt

    - name: Setup Go for Tests
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terragrunt Format
      run: |
        find . -type f -name "*.hcl" -exec terragrunt hclfmt -check {} \;

    - name: Run Tests
      run: |
        cd test
        go test -v ./...

    - name: Security Scan
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        soft_fail: false

    - name: Terragrunt Validate
      run: |
        for env in dev staging prod; do
          cd $env/eu-west-2
          terragrunt run-all validate
          cd ../../
        done
